### ISSUE TITLE
The enemies get a number on tapping 'D' key. Is this a feature or a bug

### ISSUE THREAD

**Issue by TheViTy1** [enriquesanchezb/defend-your-planet#18]
<img width="809" alt="image" src="https://github.com/enriquesanchezb/defend-your-planet/assets/153720773/5fcba1aa-4d34-4293-837e-c5594e929d07">

1.While playing the game
2. Hit d key on the keyboard

Actual Result: Numbers appear on the enemy

**Comment by enriquesanchezb** [comment]
It's a feature! It's debug mode
