### ISSUE TITLE
Score still increasing after "you lose" message

### ISSUE THREAD

**Issue by catroglio** [enriquesanchezb/defend-your-planet#5]
**Describe the bug**
Score still increasing after "you lose" message

**To Reproduce**
1. Go to game page
2. Shot on the aliens or asteroids

**Expected behavior**
Score should not increase after the game ends

**Comment by enriquesanchezb** [comment]
Fixed by [PR](https://github.com/enriquesanchezb/defend-your-planet/pull/27)
